### ISSUE TITLE
生成的cryptogen工具在生成证书的时候出了错误

### ISSUE THREAD

**Issue by jalins** [gwanted/fabric-gm#1]
![image](https://user-images.githubusercontent.com/31172582/50815664-e1ed8400-1358-11e9-9fa1-2eaf5d6e2ba8.png)

**Comment by gwanted** [comment]
哪个分支？ @Jalins

**Comment by Jalins** [comment]
> 哪个分支？ @Jalins

1.1.0分支的

**Comment by jalins** [comment]
> 哪个分支？ @Jalins

master分支

**Comment by gwanted** [comment]
把crypto-config.yaml发上来看看 @Jalins

**Comment by jalins** [comment]
> 把crypto-config.yaml发上来看看 @Jalins

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer0
        CommonName: orderer0.example.com

PeerOrgs:
  - Name: Org0
    Domain: org0.example.com
    Template:
      Count: 2
    Users:
      Count: 3
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 2
    Users:
      Count: 3

**Comment by gwanted** [comment]
用工程examples/e2e_cli例子里的crypto-config.yaml试试，貌似是你的配置文件格式有问题，decode的时候报错了 @Jalins

**Comment by jalins** [comment]
> 用工程examples/e2e_cli例子里的crypto-config.yaml试试，貌似是你的配置文件格式有问题，decode的时候报错了 @Jalins

好的，我试试，这个项目现在也支持国密的TLS通信吗？

**Comment by gwanted** [comment]
是的，支持 @Jalins
