### ISSUE TITLE
运行1.4的分支，报错

### ISSUE THREAD

**Issue by williamweb3** [gwanted/fabric-gm#4]
错误如下：
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 2 "# github.com/hyperledger/fabric/vendor/github.com/tjfoc/gmsm/vendor/golang.org/x/crypto/sha3
opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/tjfoc/gmsm/vendor/golang.org/x/crypto/sha3/keccakf_amd64.go:13:6: missing function body
# github.com/hyperledger/fabric/vendor/golang.org/x/crypto/sha3
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/sha3/keccakf_amd64.go:13:6: missing function body
# github.com/hyperledger/fabric/vendor/golang.org/x/crypto/poly1305
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/poly1305/sum_amd64.go:11:6: missing function body
# github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:15:6: missing function body
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:19:6: missing function body
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:23:6: missing function body
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:27:6: missing function body
opt/gopath/src/github.com/hyperledger/fabric/vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go:31:6: missing function body
麻烦兄弟看下是啥原因？

**Comment by gwanted** [comment]
@williamfuwei 运行make release，然后下载原版的docker镜像，用release/linux64/bin里的可执行程序替换掉docker镜像/usr/local/bin里的可执行程序

**Comment by wangxiaojianim** [comment]
@gwanted “用release/linux64/bin里的可执行程序替换掉docker镜像/usr/local/bin里的可执行程序“ 能稍解释下怎么做吗
