### ISSUE TITLE
想问下这个能正常部署运行么

### ISSUE THREAD

**Issue by AWMwhite** [gwanted/fabric-gm#6]

**Comment by AWMwhite** [comment]
为什么我尝试部署的时候，生成通道配置创世区块的时候，会报错：“main -> CRIT 005 Error on outputChannelCreateTx: config update generation failure: could not parse application to application group: setting up the MSP manager failed: admin 0 is invalid: The identity is not valid under this MSP [Org1MSP]: could not obtain certification chain: failed getting validation chain: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: SM2 verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")”

**Comment by tylerztl** [comment]
> 为什么我尝试部署的时候，生成通道配置创世区块的时候，会报错：“main -> CRIT 005 Error on outputChannelCreateTx: config update generation failure: could not parse application to application group: setting up the MSP manager failed: admin 0 is invalid: The identity is not valid under this MSP [Org1MSP]: could not obtain certification chain: failed getting validation chain: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: SM2 verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")”

我尝试了下启动报这个错误，你解决了吗？

**Comment by yinwhm12** [comment]
orderer报错: 版本1.4.3
2020-01-03 03:25:29.417 UTC [orderer.common.server] initializeLocalMsp -> FATA 021 Failed to initialize local MSP: admin 0 is invalid: could not obtain certification chain: failed getting validation chain: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: SM2 verification failure" while trying to verify candidate authority certificate "ca.example.com")

**Comment by AWMwhite** [comment]
> > 为什么我尝试部署的时候，生成通道配置创世区块的时候，会报错：“main -> CRIT 005 Error on outputChannelCreateTx: config update generation failure: could not parse application to application group: setting up the MSP manager failed: admin 0 is invalid: The identity is not valid under this MSP [Org1MSP]: could not obtain certification chain: failed getting validation chain: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: SM2 verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")”
> 
> 我尝试了下启动报这个错误，你解决了吗？

好像这个源码有问题，我换了个别的版本，可以成功部署使用
