### ISSUE TITLE
验证签名出错

### ISSUE THREAD

**Issue by bjwswang** [gwanted/fabric-gm#8]
panic: Failed to setup local msp with config: admin 0 is invalid: could not obtain certification chain: failed getting validation chain: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: SM2 verification failure" while trying to verify candidate authority certificate "ca.example.com")

在这里看到有人问了一样的问题，解决方案是换了一个全新的ubuntu18，请问下原因是什么？ 
我现在用的环境是 mac
https://www.gitmemory.com/issue/gwanted/fabric-gm/5/497224556

**Comment by bjwswang** [comment]
@gwanted 能麻烦看一下吗？ 谢谢！

**Comment by zhangbo-miuNEST** [comment]
bccsp/gm/certhelper.go这个文件中，函数ParseX509Certificate2Sm2( )在最后return之前需要增加如下代码，因为证书模板中的算法枚举值此时还都是0，没初始化，会导致生成的证书的签名不对。
我调试好久才找到这个bug。由于这个bug的存在，repo主人的代码是没法用的，这个bug是critical的。

```
	if sm2cert.SignatureAlgorithm == sm2.UnknownSignatureAlgorithm {
		sm2cert.SignatureAlgorithm = sm2.SM2WithSM3
	}

	if sm2cert.PublicKeyAlgorithm == sm2.UnknownPublicKeyAlgorithm {
		sm2cert.PublicKeyAlgorithm = sm2.ECDSA
	}

```
